kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1alpha1
providers:
  # returns 'Global' cache key type
  - name: gcr
    matchImages:
    - "container.cloud.google.com"
    - "gcr.io"
    - "*.gcr.io"
    - "*.pkg.dev"
    defaultCacheDuration: 1m
    apiVersion: "credentialprovider.kubelet.k8s.io/v1alpha1"
