kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1alpha1
providers:
  # returns 'Registry' cache key type
  - name: acr
    matchImages:
    - "*.azurecr.io"
    - "*.azurecr.cn"
    - "*.azurecr.de"
    - "*.azurecr.us"
    defaultCacheDuration: 1m
    apiVersion: "credentialprovider.kubelet.k8s.io/v1alpha1"
    env:
    - name: "AZURE_CONTAINER_REGISTRY_CONFIG"
      value: "/etc/azure/azure-registry-config.yaml"
